version: '3.8'

services:
  spring-app:
#    build: .
    image: ${DOCKER_USERNAME}/ahanon
    container_name: AhanOn_Container
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - DB_HOST=mysql-db
      - REDIS_HOST=redis-cache
      - REDIS_PORT=6379
    depends_on:
      - mysql-db
      - redis-cache
    restart: always

  mysql-db:
    image: mysql:8.0
    container_name: AhanOn_MySQL
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
      # 배치 테이블 초기화 스크립트 마운트 (옵션)
      - ./src/main/resources/sql/batch_table_init.sql:/docker-entrypoint-initdb.d/batch_table_init.sql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always

  redis-cache:
    image: redis:7-alpine # 가벼운 alpine 이미지 사용
    container_name: AhanOn_Redis
    ports:
      - "6379:6379" # 호스트와 컨테이너 포트 매핑
    volumes:
      - redis_data:/data # 데이터 영속성을 위한 볼륨
    restart: always

volumes:
  mysql_data: # 데이터 영속성을 위한 볼륨 정의
  redis_data: # 볼륨 정의의
