name: Ahan_On WorkFlow

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checking repository...
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: login docker...
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}

      - name: build & push docker image...
        run: |
          chmod +x ./gradlew
          docker build -t ${{secrets.DOCKER_USERNAME}}/ahanon .
          docker push ${{secrets.DOCKER_USERNAME}}/ahanon

      - name: deploy to EC2...
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.EC2_HOST}}
          username: ${{secrets.EC2_USERNAME}}
          key: ${{secrets.EC2_PRIVATE_KEY}}
          script: |
            if [ -d "ahanon" ]; then
              echo "Git repository already exists. Pulling !!"
              cd AhanOn
              sudo git pull origin main
            else
              echo "Git repository not found. Cloning !!!"
              git clone https://github.com/It-s-dangerous-inside-the-blanket/BE.git
              cd AhanOn
            fi
            
            sudo docker-compose down || true

            echo "DB_HOST=mysql-db" > .env 
            echo "DB_NAME=${{secrets.DB_NAME}}" >> .env
            echo "DB_USERNAME=${{secrets.DB_USERNAME}}" >> .env
            echo "DB_PASSWORD=${{secrets.DB_PASSWORD}}" >> .env
            echo "GEMINI_KEY=${{secrets.GEMINI_KEY}}" >> .env
            
            sudo docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
            
            sudo docker-compose pull
            sudo docker-compose up -d
